accounts/urls.py
from django.urls import path, include, re_path

from django.contrib.auth import views as auth_views

app_name = 'accounts'

from accounts import views

urlpatterns = [
	re_path(r'^login/$', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
	re_path(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
	path('profile/', views.Profile, name='profile'),
	path('profile/disconnect/', views.FacebookProfileDisconnect, name='profile-disconnect'),
]

social_sweethearts/urls.py
from django.urls import path, include, re_path

urlpatterns = [
	path('accounts/', include('accounts.urls', namespace='accounts')),
	re_path(r'^oauth/', include('social_django.urls', namespace='social')),  # from social-auth-app-django
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from django.views.decorators.csrf import csrf_exempt

from social_django.models import UserSocialAuth

import requests

@login_required
def Profile(request):
	if request.method == "GET":
		try:
			facebook_auth = request.user.social_auth.get(provider='facebook')
		except UserSocialAuth.DoesNotExist:
			facebook_auth = None
		if facebook_auth:
			# reading profile picture doesn't require an access token or permission
			# if you want to get JSON response simply put redirect=false in your query parameter
			FACEBOOK_PROFILE = f"https://graph.facebook.com/v3.3/{facebook_auth.uid}/picture"
			response = requests.get(FACEBOOK_PROFILE, params={'height':300, 'width':300, 'redirect':'false'})

			if response.status_code == 200:
				response.encoding = 'utf-8'
				profile_image = response.json()['data']['url']
	return render(request, 'accounts/profile.html', {'profile_image':profile_image})


@csrf_exempt
def FacebookProfileDisconnect(request):
	if request.method == 'POST':
		print(request.POST)
	return redirect('accounts:login')

templates/accounts/profile.html
{% extends '../base.html' %}
{% load static %}
{% block title %}Social Sweethearts | Profile{% endblock title %}
{% block body %}
        <div id="wrapper">

            <!-- Navigation -->
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'accounts:profile' %}">Social Sweethearts</a>
                </div>

                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <ul class="nav navbar-nav navbar-left navbar-top-links">
                    <li><a href="#"><i class="fa fa-home fa-fw"></i> Website</a></li>
                </ul>

                <ul class="nav navbar-right navbar-top-links">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-user fa-fw"></i> {{ user.username }} <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="{% url 'accounts:profile' %}"><i class="fa fa-user fa-fw"></i> User Profile</a>
                            </li>
                            <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                            </li>
                            <li class="divider"></li>
                            <li><a href="{% url 'accounts:logout' %}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                            </li>
                        </ul>
                    </li>
                </ul>
                <!-- /.navbar-top-links -->

                <div class="navbar-default sidebar" role="navigation">
                    <div class="sidebar-nav navbar-collapse">
                        <ul class="nav" id="side-menu">
                            <li class="sidebar-search">
                                <div class="input-group custom-search-form">
                                    <input type="text" class="form-control" placeholder="Search...">
                                    <span class="input-group-btn">
                                        <button class="btn btn-primary" type="button">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </span>
                                </div>
                                <!-- /input-group -->
                            </li>
                            <li>
                                <a href="{% url 'accounts:profile'%}"><i class="fa fa-user fa-fw"></i> Profile</a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.sidebar-collapse -->
                </div>
                <!-- /.navbar-static-side -->
            </nav>

            <!-- Page Content -->
            <div id="page-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <h1 class="page-header">Name | {{ user.first_name }} {{ user.last_name }}</h1>
                            <h1 class="page-header">Profile Photo</h1>
                            <img src="{{ profile_image }}">
                        </div>
                        <!-- /.col-lg-12 -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- /#page-wrapper -->

        </div>
        <!-- /#wrapper -->
{% endblock body %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        {% block header %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>{% block title %}Social Sweethearts | Base {% endblock %}</title>

        <!-- Bootstrap Core CSS -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

        <!-- MetisMenu CSS -->
        <link href="{% static 'css/metisMenu.min.css' %}" rel="stylesheet">

        <!-- Social Buttons CSS -->
        <link href="{% static 'css/bootstrap-social.css' %}" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="{% static 'css/startmin.css' %}" rel="stylesheet">

        <!-- Custom Fonts -->
        <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        {% endblock header %}
    </head>
    <body>
        {% block body %}

        {% endblock body %}
        {% block footer %}
        <!-- jQuery -->
        <script src="{% static 'js/jquery.min.js' %}"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="{% static 'js/bootstrap.min.js' %}"></script>

        <!-- Metis Menu Plugin JavaScript -->
        <script src="{% static 'js/metisMenu.min.js' %}"></script>

        <!-- Custom Theme JavaScript -->
        <script src="{% static 'js/startmin.js' %}"></script>
        {% endblock footer %}
    </body>
</html>